### ISSUE TITLE
App not visible

### ISSUE THREAD

**Issue by mfumagalli68** [miraisolutions/SmaRP#139] opened 2019-06-25 13:24 UTC
Hi. 

I've heard of your application during a talk that your colleague Francesca held in Italy a few months ago.
I was checking your app and every time i click on the link the app is not usable, grey screen , no plot, no interaction possible. ( See screenshot below)

![Screenshot (5)](https://user-images.githubusercontent.com/20440242/60101987-1913ee00-975d-11e9-9df8-2190f22be5d5.png)

Maybe you are well aware of this issue, in that case I apologize for the useless issue.

Thanks

**Comment by gabrielfoix** [comment] 2019-06-25 19:59
Many thanks for your issue. 
To be able to reproduce it, could you please let us know which version of Chrome and Windows are you using? 
Have you experienced the same issue in different networks? At home which your private laptop, in the office, etc.

**Comment by mfumagalli68** [comment] 2019-06-27 07:00
Chrome 75.0.3770, Windows 10  office laptop.
Ubuntu 18.04 and Chrome 75.0.37770 personal laptop.

At office, i think I'm behind a proxy and so probably that's the reason why I can't use the app. Indeed at home with my office laptop using my home connection it works. Weird thing is that the app doesn't work on my personal laptop ( ubuntu one).

**Comment by riccardoporreca** [comment] 2019-06-28 09:23
@mfumagalli68 

- Indeed, being behind a proxy is a known issue that prevents interacting with the app. We are actually in the process of reviewing the way we deploy and expose SmaRP, we can consider looking at the _behind proxy_ more in detail along the way.
- We can successfully use the app from Ubuntu 18.04 with the very same version of Chrome as well using other browsers like Firefox. You may have some special network settings in your Ubuntu installation or browser configuration.

We will probably close this issue in the coming days.

**Comment by gabrielfoix** [comment] 2019-07-02 09:55
Checks performed successfully. 
Since no further actions can be taken on, we close the issue.

**Closed by gabrielfoix** 2019-07-02 09:55 UTC
